services:
  yak-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./tools:/app/tools
      - ./license_data:/app/license_data
      - ./dual_keys:/app/dual_keys
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app/src
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s